// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "about_section": {
    "eyebrow"?: string;
    "title"?: string;
    "body"?: string;
    "image"?: string;
  };
  "account": {
    "heading"?: string;
  };
  "cart_summary": {
    "title"?: string;
    "checkout_label"?: string;
    "empty_title"?: string;
    "empty_cta_label"?: string;
    "empty_cta_link"?: string;
  };
  "categories": {
    "title"?: string;
    "columns_desktop"?: number;
  };
  "featured_collection": {
    "title"?: string;
    "tab_trending_label"?: string;
    "tab_bestseller_label"?: string;
    "tab_new_label"?: string;
    "view_all_label"?: string;
    "view_all_link"?: string;
    "max_items"?: number;
  };
  "footer": {
    "brand_name"?: string;
    "description"?: string;
    "ticker_text"?: string;
    "instagram"?: string;
    "facebook"?: string;
    "twitter"?: string;
    "copyright"?: string;
  };
  "frequently_bought": {
    "enabled"?: boolean;
    "title"?: string;
    "max_items"?: number;
  };
  "header": {
    "brand_name"?: string;
    "logo"?: string;
    "announcement_text"?: string;
    "menu_handle"?: string;
    "show_search"?: boolean;
    "show_account"?: boolean;
    "show_cart"?: boolean;
  };
  "hero": {
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_1"?: string;
    "image_2"?: string;
    "image_3"?: string;
    "autoplay"?: boolean;
  };
  "image_with_text": {
    "eyebrow"?: string;
    "title"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image"?: string;
    "image_position"?: "start" | "end" | "background";
    "overlay"?: boolean;
  };
  "marquee": {
    "text"?: string;
    "repeat"?: number;
  };
  "newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "not_found": {
    "code"?: string;
    "title"?: string;
    "message"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "order_confirmation": {
    "title"?: string;
    "subtitle"?: string;
  };
  "product_details": {
    "add_to_cart_label"?: string;
    "show_compare_price"?: boolean;
    "show_related"?: boolean;
    "show_whatsapp"?: boolean;
    "show_fbt"?: boolean;
  };
  "product_grid": {
    "title"?: string;
    "columns_desktop"?: number;
    "show_search"?: boolean;
    "show_sort"?: boolean;
    "show_categories"?: boolean;
  };
  "promo_banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
  };
  "rich_text": {
    "title"?: string;
    "content"?: string;
    "align"?: "start" | "center";
    "width"?: "narrow" | "wide";
  };
  "search_results": {
    "title"?: string;
    "search_placeholder"?: string;
    "no_results_text"?: string;
    "columns_desktop"?: number;
  };
  "size_chart": {
    "trigger_label"?: string;
    "title"?: string;
  };
  "testimonials": {
    "title"?: string;
  };
}
